/**
 * Sunshine Conversations API
 *
 * The version of the OpenAPI document: 16.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MetaConversionEvent from './MetaConversionEvent';

/**
 * The WhatsAppConversionEventsBody model module.
 * @module sunshine-conversations-client/sunshine-conversations-client.model/WhatsAppConversionEventsBody
 * @version 16.0.1
 */
class WhatsAppConversionEventsBody {
    /**
     * Constructs a new <code>WhatsAppConversionEventsBody</code>.
     * @alias module:sunshine-conversations-client/sunshine-conversations-client.model/WhatsAppConversionEventsBody
     */
    constructor() { 
        
        WhatsAppConversionEventsBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WhatsAppConversionEventsBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:sunshine-conversations-client/sunshine-conversations-client.model/WhatsAppConversionEventsBody} obj Optional instance to populate.
     * @return {module:sunshine-conversations-client/sunshine-conversations-client.model/WhatsAppConversionEventsBody} The populated <code>WhatsAppConversionEventsBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WhatsAppConversionEventsBody();

            if (data.hasOwnProperty('whatsapp')) {
                obj['whatsapp'] = MetaConversionEvent.constructFromObject(data['whatsapp']);
            }
        }
        return obj;
    }

/**
     * @return {module:sunshine-conversations-client/sunshine-conversations-client.model/MetaConversionEvent}
     */
    getWhatsapp() {
        return this.whatsapp;
    }

    /**
     * @param {module:sunshine-conversations-client/sunshine-conversations-client.model/MetaConversionEvent} whatsapp
     */
    setWhatsapp(whatsapp) {
        this['whatsapp'] = whatsapp;
    }

}

/**
 * @member {module:sunshine-conversations-client/sunshine-conversations-client.model/MetaConversionEvent} whatsapp
 */
WhatsAppConversionEventsBody.prototype['whatsapp'] = undefined;






export default WhatsAppConversionEventsBody;

